p2pu/p2pu-website

- en/jobs.markdown
> Update text for web design job

- _data/people.yml
P2PU was founded in 2008, initial discussions took place in 2007
> Updated Philipp's bio

- en/about/index.html
See email discussion. Agree that we should take more time for the bigger redesign.
> Mini update (added founding year)

- Gemfile.lock
- _data/navigation.yml
- _includes/nav.html
- _sass/_menu.scss
- assets/react/components/NavAccount.jsx
- assets/react/constants.js
- assets/react/helpers/ApiHelper.js
- assets/react/navbar.jsx
- en/index.html
This depends on the 2018-01-create-api branch on the learning-circles project, so hold off merging this until that branch is merged.
> account nav item on navbar

- _includes/scripts.html
- en/index.html
> require navbar bundle in scripts so it loads on all pages

- package.json
> next version of p2pu-search-cards to fix background colours and titles

- _sass/_index.scss
- _sass/_menu.scss
- assets/react/components/NavAccount.jsx
- assets/react/constants.js
> add permanent login link

- _sass/_index.scss
- assets/react/components/Home/MeetingsPreview.jsx
- en/facilitate/index.html
- package-lock.json
- package.json
> fix typo on facilitate page and use latest p2pu-search-cards version

- assets/react/components/Facilitate/ResourceCategory.jsx
> put row class at the right level

- _sass/_index.scss
- en/index.html
> replace photo with youtube video

- assets/react/components/Facilitate/DiscourseCommunity.jsx
- assets/react/components/Home/HeaderTextCarousel.jsx
... also some minor cleanup on typist component
Fixes https://github.com/p2pu/learning-circles/issues/418
> make sure category is never undefined in FAQs table on /facilitate

- _data/teams.json
- _sass/_teams.scss
- en/teams/index.html
- s3_website.yml
> fix team page urls, Akron coordinates, and team card header image height

- _data/testimonials.yml
- _includes/testimonial.html
- _sass/_index.scss
- assets/js/index.js
- assets/react/components/Home/BrowseMeetings.jsx
- assets/react/components/Home/DiscourseCommunity.jsx
- assets/react/components/Home/EventsFeed.jsx
- assets/react/components/Home/MeetingCard.jsx
- assets/react/components/Home/TeamsFeed.jsx
- assets/react/constants.js
- assets/react/landing-view.jsx
- en/index.html
Depends on https://github.com/p2pu/learning-circles/pull/496 and https://github.com/p2pu/learning-circles/pull/487
> Homepage update v2

- en/facilitate/index.html
> Add link to create a learning circle earlier on facilitate page

- _includes/team_page_script.html
- _layouts/search.html
- _layouts/team.html
- _sass/_organizer_profile.scss
- _sass/_team.scss
- assets/react/search.jsx
- assets/react/team-subtitle.jsx
- en/learning-circles/index.html
- en/teams/index.html
- use formatted text
- update team page with data from API
- fix some weirdness with logo and image styles
- fixes #339 
Here are the instructions for organizers on updating their team page: 
https://docs.google.com/document/d/1v1hKUYSYLpal6SqeAliC_HcuAYwFRl8Iy8KHIFpCbPk/edit#heading=h.u0j8kcn6w9dp
> Rich text team intro

- package-lock.json
- package.json
get latest changes:
- set cursor to pointer on button cards
- use yellow for past lcs
- revert to js masonry component
> bump p2pu-components

- _includes/team_page_script.html
- _layouts/team.html
- assets/react/constants.js
- assets/react/search.jsx
- en/learning-circles/index.html
**Deploying site to**: [p2pu-website-active-swine.s3-website-us-east-1.amazonaws.com
](http://p2pu-website-active-swine.s3-website-us-east-1.amazonaws.com
)
> Pass API origin to react component using HTML dataset property.

- package-lock.json
- package.json
**Deploying site to**: [p2pu-website-fair-dinosaur.s3-website-us-east-1.amazonaws.com
](http://p2pu-website-fair-dinosaur.s3-website-us-east-1.amazonaws.com
)
> S kennedy lc cards

- package-lock.json
- package.json
Relevant commits: 
https://github.com/p2pu/p2pu-components/commit/e4adf378ba6841fcab3dbf8c919e52ed3c2b701e
https://github.com/p2pu/p2pu-components/commit/00c968dc3685c4f75881b9cfbacb431cc9496e6a
https://github.com/p2pu/p2pu-components/commit/a0c39b2e9404530d069c8e4dc44bcc063f003e82
Fixes https://github.com/p2pu/learning-circles/issues/737 and https://github.com/p2pu/learning-circles/issues/736
Depends on https://github.com/p2pu/learning-circles/pull/742
> use lc status from api

- _includes/team_page_script.html
- _layouts/team.html
**Deploying site to**: [p2pu-website-unique-beetle.s3-website-us-east-1.amazonaws.com
](http://p2pu-website-unique-beetle.s3-website-us-east-1.amazonaws.com
)
> Read subtitle on team page from API data

- package-lock.json
- package.json
**Deploying site to**: [p2pu-website-better-marmot.s3-website-us-east-1.amazonaws.com
](http://p2pu-website-better-marmot.s3-website-us-east-1.amazonaws.com
)
> bump p2pu-components version to use lc card with meeting frequency

- _data/people.yml
- en/jobs.md
- en/jobs/website-redesign.md
**Deploying site to**: ["p2pu-website-lasting-tick.s3-website-us-east-1.amazonaws.com"
](http://"p2pu-website-lasting-tick.s3-website-us-east-1.amazonaws.com"
)
> 2021-02-16 Release - add project ad for website redesign

- en/jobs/website-redesign.md
**Deploying site to**: ["p2pu-website-thorough-perch.s3-website-us-east-1.amazonaws.com"
](http://"p2pu-website-thorough-perch.s3-website-us-east-1.amazonaws.com"
)
> updated headers to be consistently h2

- .github/workflows/website-deploy.yml
- .github/workflows/website-staging.yml
- README.md
**Deploying site to**: [p2pu-website-regular-tick.s3-website-us-east-1.amazonaws.com](http://p2pu-website-regular-tick.s3-website-us-east-1.amazonaws.com)
> Update for demonstrative purposes

- _sass/_about.scss
- en/about/index.html
Add page anchor for teams section on about page
> Delta release 2021-12-02

- _data/navigation.yml
- assets/css/p2pu-custom.scss
- en/events/index.html
**Deploying site to**: http://p2pu-website-solid-lion.s3-website-us-east-1.amazonaws.com
> Events calendar

- _data/navigation.yml
**Deploying site to**: http://p2pu-website-loved-hound.s3-website-us-east-1.amazonaws.com
> Release 2021-12-14 - Add teams subnav

- _data/landing_page_cards.yml
- error.html
> 2022-01-04 Content update

- .github/workflows/website-staging.yml
- .terraform.lock.hcl
- collegeunbound/index.html
- terraform.tf
http://p2pu-website-happy-hare.s3-website-us-east-1.amazonaws.com/en/
> Add new page for college unbound learning circles

- collegeunbound/index.html
**Deploying site to**: http://p2pu-website-relaxing-duck.s3-website-us-east-1.amazonaws.com
> Filter courses on collegeunbound page

- en/about/index.html
- en/teams/index.html
**Deploying site to**: http://p2pu-website-flexible-tortoise.s3-website-us-east-1.amazonaws.com
> Move teams to teams page

- .github/workflows/website-staging.yml
- README.md
**Deploying site to**: http://p2pu-website-humorous-crow.s3-website-us-east-1.amazonaws.com
> Add online / in-person filter to learning circle search

- _layouts/topic_detail.html
- _topics/antiracism.md
- _topics/business-and-entrepreneurship.md
- _topics/climate-change.md
- _topics/communication.md
- _topics/computer-programming.md
- _topics/creativity.md
- _topics/digital-literacy.md
- _topics/history.md
- _topics/job-readiness.md
- _topics/language-learning.md
- _topics/science.md
> Release 2022-10-27

- _data/people.yml
Move June from the board to past collaborators
> Release 2022-10-28 - Content update

- _data/navigation.yml
- _includes/head.html
- _includes/page_header.html
- _layouts/topic_detail.html
- _sass/_courses.scss
- en/learning-resources/index.html
- en/topics/index.html
**Deploying site to**: http://p2pu-website-obliging-swift.s3-website-us-east-1.amazonaws.com
> Split learning resources page

- _config.yml
**Deploying site to**: http://p2pu-website-real-sponge.s3-website-us-east-1.amazonaws.com
> Release 2023-02-07

- .github/workflows/website-staging.yml
- _deploy/s3_redirects.sh
- terraform.tf
**Deploying site to**: http://p2pu-website-peaceful-newt.s3-website-us-east-1.amazonaws.com
> Fixing GitHub workflow for staging

- .github/workflows/website-staging.yml
**Deploying site to**: http://p2pu-website-valued-herring.s3-website-us-east-1.amazonaws.com
> Update version of terraform github action

- _data/navigation.yml
- en/index.html
**Deploying site to**: http://p2pu-website-related-troll.s3-website-us-east-1.amazonaws.com
> Update site navigation

- _data/landing_page_cards.yml
> Release 2024-11-04 - Copy Tweaks

- _data/landing_page_cards.yml
> Release 2024-11-26 - Content update

- _data/landing_page_cards.yml
**Deploying site to**: http://p2pu-website-fun-flamingo.s3-website-us-east-1.amazonaws.com
> Release 2024-12-12 - content update

- _includes/fundraise_up.html
- _includes/head.html
- en/index.html
> Release 2025-05-15
